variables:
  CONTAINER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}_${CI_COMMIT_SHORT_SHA}
  CONTAINER_IMAGE_LATEST: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  CONTAINER_IMAGE_DEVELOP: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}
  CONTAINER_IMAGE_MASTER: ${CI_REGISTRY}/${CI_PROJECT_PATH}:php-7.2
  CONTAINER_IMAGE_TAG: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_TAG}
docker-build-other:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

    - export CI_BUILD_TIMESTAMP=$(TZ='Asia/Bangkok' date -Iseconds)
    - export CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA}
    - export CI_COMMIT_BRANCH=${CI_COMMIT_BRANCH}
  script:
    - docker build -t ${CONTAINER_IMAGE} .
    # - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_LATEST}
    # - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_DEVELOP}
    # - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_DEVELOP}
  except:
    - master
docker-build-master:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

    - export CI_BUILD_TIMESTAMP=$(TZ='Asia/Bangkok' date -Iseconds)
    - export CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA}
    - export CI_COMMIT_BRANCH=${CI_COMMIT_BRANCH}
  script:
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_LATEST}
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_MASTER}
    # - docker push ${CONTAINER_IMAGE}
    # - docker push ${CONTAINER_IMAGE_DEVELOP}
  only:
    - master
    
docker-build-tag:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

    - export CI_BUILD_TIMESTAMP=$(TZ='Asia/Bangkok' date -Iseconds)
    - export CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA}
    - export CI_COMMIT_BRANCH=${CI_COMMIT_BRANCH}
  script:
    - docker build -t ${CONTAINER_IMAGE} .
    # - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_LATEST}
    # - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_DEVELOP}
    # - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_LATEST}
    - docker push ${CONTAINER_IMAGE_TAG}
  only:
    - tag